# Generated by Django 5.2.5 on 2026-06-30 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_sparepart_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='Name of the person the part was issued/given to (free text, used if recipient is not a system user).', max_length=150),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='recipient_user',
            field=models.ForeignKey(blank=True, help_text='Select the recipient from existing system users, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
