# Generated by Django 5.2.5 on 2026-06-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stocktransaction_recipient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='ticket_number',
            field=models.CharField(blank=True, help_text='Optional support/job ticket number associated with this transaction (entered manually).', max_length=100),
        ),
    ]
