# Generated by Django 5.2.5 on 2026-01-05 13:28

from django.db import migrations
from encrypted_model_fields.fields import EncryptedCharField

def encrypt_existing_data(apps, schema_editor):
    """
    Safely encrypt existing plain-text data
    """
    Profile = apps.get_model('core', 'Profile')
    
    # Get all profiles with data
    profiles_to_update = []
    for profile in Profile.objects.all():
        if profile.phone_number or profile.id_number:
            profiles_to_update.append({
                'id': profile.id,
                'phone': profile.phone_number,
                'id_num': profile.id_number,
            })
    
    print(f"Found {len(profiles_to_update)} profiles to encrypt")
    
    # After the field type changes, re-save to encrypt
    # This happens AFTER AlterField operations below
    for data in profiles_to_update:
        try:
            profile = Profile.objects.get(id=data['id'])
            # Re-assign the values - they'll be encrypted on save
            profile.phone_number = data['phone']
            profile.id_number = data['id_num']
            profile.save()
            print(f"✅ Encrypted profile {data['id']}")
        except Exception as e:
            print(f"❌ Error encrypting profile {data['id']}: {e}")

def decrypt_data_if_reverting(apps, schema_editor):
    """
    If we need to rollback, convert back to plain text
    """
    Profile = apps.get_model('core', 'Profile')
    
    for profile in Profile.objects.all():
        # Django will auto-decrypt when reading
        phone = profile.phone_number
        id_num = profile.id_number
        
        # Just re-save - will store as plain text after field type reverts
        profile.phone_number = phone
        profile.id_number = id_num
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_id_number_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=EncryptedCharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_number',
            field=EncryptedCharField(blank=True, max_length=20, null=True),
        ),
        # Step 2: Encrypt existing data
        migrations.RunPython(
            encrypt_existing_data, 
            reverse_code=decrypt_data_if_reverting
        ),
    ]
