# Generated by Django 5.2.5 on 2026-01-12 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_file_uploaded_by_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
    ]
