# Generated by Django 5.2.5 on 2026-01-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_zone_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
