# Generated by Django 5.2.5 on 2026-01-15 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ticket_last_activity_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='last_activity_at',
        ),
    ]
