# Generated by Django 5.2.5 on 2026-02-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_ticket_last_activity_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
    ]
