# Generated by Django 5.2.5 on 2026-02-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_ticket_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='job_card_number',
            field=models.CharField(blank=True, help_text='Required for all units except Remote Support', max_length=100, null=True),
        ),
    ]
