# Generated by Django 5.2.5 on 2026-04-30 11:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ticket_job_card_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('month', models.DateField(help_text='Month this claim covers (use first day of month)')),
                ('advance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('manager_approved', 'Manager Approved'), ('hr_approved', 'HR Approved'), ('finance_approved', 'Finance Approved'), ('rejected', 'Rejected')], default='draft', max_length=30)),
                ('manager_comment', models.TextField(blank=True)),
                ('hr_comment', models.TextField(blank=True)),
                ('finance_comment', models.TextField(blank=True)),
                ('manager_actioned_at', models.DateTimeField(blank=True, null=True)),
                ('hr_actioned_at', models.DateTimeField(blank=True, null=True)),
                ('finance_actioned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_forms', to=settings.AUTH_USER_MODEL)),
                ('finance_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_to_finance_review', to=settings.AUTH_USER_MODEL)),
                ('hr_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_to_hr_review', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_to_manage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('site', models.CharField(max_length=200)),
                ('job_card_id', models.CharField(blank=True, max_length=100)),
                ('transport_to', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('transport_from', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('breakfast', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('lunch', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('dinner', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('bed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.claimform')),
            ],
            options={
                'ordering': ['date', 'order'],
            },
        ),
    ]
