# Generated by Django 5.2.5 on 2026-05-07 22:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_claimform_claimentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimform',
            old_name='hr_actioned_at',
            new_name='finance_paid_at',
        ),
        migrations.RemoveField(
            model_name='claimentry',
            name='job_card_id',
        ),
        migrations.RemoveField(
            model_name='claimform',
            name='hr_comment',
        ),
        migrations.RemoveField(
            model_name='claimform',
            name='hr_reviewer',
        ),
        migrations.AddField(
            model_name='claimentry',
            name='ticket_number',
            field=models.CharField(blank=True, help_text='Ticket / job reference number', max_length=100),
        ),
        migrations.AddField(
            model_name='claimentry',
            name='ticket_url',
            field=models.URLField(blank=True, help_text='Direct URL to the ticket (optional)', max_length=500),
        ),
        migrations.AddField(
            model_name='claimform',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount actually disbursed by Finance', max_digits=10),
        ),
        migrations.AddField(
            model_name='claimform',
            name='finance_paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_paid_out', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='claimform',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('manager_approved', 'Manager Approved'), ('finance_approved', 'Finance Approved'), ('rejected', 'Rejected')], default='draft', max_length=30),
        ),
    ]
