# Generated by Django 5.2.5 on 2026-05-11 12:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_hr_actioned_at_claimform_finance_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimform',
            name='carry_forward',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance carried forward from the previous approved claim', max_digits=10),
        ),
        migrations.AddField(
            model_name='claimform',
            name='previous_claim',
            field=models.ForeignKey(blank=True, help_text='The prior approved claim whose balance was carried into this one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_claims', to='core.claimform'),
        ),
    ]
