# Generated by Django 5.2.5 on 2026-05-18 08:22

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_claimform_carry_forward_claimform_previous_claim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimform',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount actually disbursed by Finance (sum of payment records)', max_digits=10),
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount disbursed in this payment', max_digits=10)),
                ('note', models.CharField(blank=True, help_text="Optional note (e.g. 'Partial payment — balance pending')", max_length=255)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='core.claimform')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['paid_at'],
            },
        ),
    ]
