# Generated by Django 5.2.5 on 2026-06-08 11:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_claimform_amount_paid_paymentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimentry',
            name='other_expenditure',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
