# Generated by Django 5.2.5 on 2026-06-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_claimform_suggested_amount_claimform_suggested_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimform',
            name='suggested_amount',
        ),
        migrations.RemoveField(
            model_name='claimform',
            name='suggested_at',
        ),
        migrations.RemoveField(
            model_name='claimform',
            name='suggested_by',
        ),
        migrations.AlterField(
            model_name='claimform',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('manager_approved', 'Manager Approved'), ('finance_approved', 'Finance Approved'), ('rejected', 'Rejected')], default='draft', max_length=30),
        ),
    ]
