# Generated by Django 5.2.5 on 2026-06-30 09:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_claimform_suggested_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claimform',
            name='suggested_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount the manager recommends Finance disburse to the employee', max_digits=10),
        ),
        migrations.AddField(
            model_name='claimform',
            name='suggested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimform',
            name='suggested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_suggested_amount', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='claimform',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('manager_approved', 'Manager Approved'), ('finance_approved', 'Finance Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='draft', max_length=30),
        ),
    ]
