# Generated by Django 5.2.5 on 2026-06-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_claimform_suggested_amount_claimform_suggested_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimform',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('manager_approved', 'Manager Approved'), ('pending_disbursement', 'Pending Disbursement'), ('finance_approved', 'Closed'), ('rejected', 'Rejected')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='claimform',
            name='suggested_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount the manager recommends Finance disburse', max_digits=10, null=True),
        ),
    ]
