# Generated by Django 5.2.5 on 2026-07-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_claimform_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimentry',
            name='other_expenditure_note',
            field=models.CharField(blank=True, help_text="Brief explanation of what the 'Other Expenditure' amount was for", max_length=255),
        ),
    ]
