# Generated by Django 5.2.3 on 2025-08-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_ticket_escalation_action_ticket_escalation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(blank=True, default="Customer", max_length=100),
        ),
    ]
