# Generated by Django 5.2.3 on 2025-08-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_alter_profile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(blank=True, default="Guest", max_length=100),
        ),
    ]
