# Generated by Django 5.2.3 on 2025-09-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0065_alter_profile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Director", "Director"),
                    ("Manager", "Manager"),
                    ("Staff", "Staff"),
                    ("Customer", "Customer"),
                    ("Overseer", "Overseer"),
                    ("Custodian", "Custodian"),
                    ("Guest", "Guest"),
                ],
                default="Guest",
                max_length=50,
            ),
        ),
    ]
