# Generated by Django 5.2.3 on 2025-09-03 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_ticket_zone_alter_ticket_status_usernotification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activitylog",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="responsible",
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(max_length=1000),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["ticket", "timestamp"], name="core_activi_ticket__ae1828_idx"
            ),
        ),
    ]
