# Generated by Django 5.2.5 on 2025-09-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_ticket_responsible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
