# Generated by Django 5.2.5 on 2025-09-08 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_remove_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='comment_summary',
        ),
    ]
