# Generated by Django 5.2.5 on 2025-09-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_remove_ticket_comment_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comment_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
