# Generated by Django 5.2.5 on 2025-09-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_ticket_comment_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_unassigned_notification',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
