# Generated by Django 5.2.5 on 2025-09-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_ticket_assigned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('new', 'New'), ('escalated', 'Escalated'), ('unassigned', 'Unassigned')], default='new', max_length=20),
        ),
    ]
