# Generated by Django 5.2.5 on 2025-09-09 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_usernotification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usernotification',
            name='unique_user_ticket_notification',
        ),
        migrations.AddConstraint(
            model_name='usernotification',
            constraint=models.UniqueConstraint(fields=('user', 'ticket', 'notification_type'), name='unique_user_ticket_notification'),
        ),
    ]
