# Generated by Django 5.2.5 on 2025-09-09 20:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_remove_usernotification_unique_user_ticket_notification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usernotification',
            name='unique_user_ticket_notification',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='notification_type',
        ),
        migrations.AddConstraint(
            model_name='usernotification',
            constraint=models.UniqueConstraint(fields=('user', 'ticket'), name='unique_user_ticket_notification'),
        ),
    ]
