# Generated by Django 5.2.5 on 2025-09-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_remove_usernotification_unique_user_ticket_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_sla_breached',
            field=models.BooleanField(default=False),
        ),
    ]
