# Generated by Django 5.2.5 on 2025-09-18 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_usernotification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('level', models.PositiveIntegerField()),
                ('recipients', models.TextField(help_text='Comma-separated list of email addresses for this tier')),
                ('max_for_priority', models.JSONField(blank=True, null=True)),
                ('sla_minutes', models.PositiveIntegerField(default=30)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='current_escalation_level',
        ),
        migrations.AddField(
            model_name='ticket',
            name='current_escalation_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='core.escalationtier'),
        ),
    ]
