# Generated by Django 5.2.5 on 2025-09-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_escalationtier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='current_escalation_tier',
        ),
        migrations.AddField(
            model_name='ticket',
            name='current_escalation_level',
            field=models.CharField(blank=True, choices=[('Tier 1', 'Tier 1'), ('Tier 2', 'Tier 2'), ('Tier 3', 'Tier 3'), ('Tier 4', 'Tier 4')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='EscalationTier',
        ),
    ]
